### ISSUE TITLE
pretrained model come from?

### ISSUE THREAD

**Issue by meijieru** [DrSleep/tensorflow-deeplab-resnet#103]
The `deeplab_resnet_init.ckpt` seems to come from model pretrained on mscoco.
So what about `deeplab_resnet.ckpt`?

**Comment by nbei** [comment]
Oh, I also really wanna to know the source of the 2 'ckpt' file. Could you please specify something about them? @DrSleep  Thanks!
And BTW, I could not use your convert.py to transfer the init.caffemodel to npy. It report an error like this:  `google.protobuf.text_format.ParseError: 18:5 : Message type "caffe.TransformationParameter" has no field named "scale_factors".`

**Comment by DrSleep** [comment]
refer to [this](http://liangchiehchen.com/projects/DeepLabv2_resnet.html) and [this](https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/19)
