### ISSUE TITLE
Train on new dataset, error for different num classes

### ISSUE THREAD

**Issue by NitishMutha** [DrSleep/tensorflow-deeplab-resnet#105]
I am trying to train the model on different dataset with 60 classes. Made all the changes as per the steps mentioned on readme file. But then when i restore the deeplab_resnet.ckpt then i get an error saying:
 
 Assign requires shapes of both tensors to match. lhs shape= [60] rhs shape= [21]

Since the restore file was created with 21 classes. So in that case I will have to train the whole model from scratch with random weights initialized for resnet? Would that work?

**Comment by hellochick** [comment]
hey, 
u can add flag "--not-restore-last" to solve this problem

**Comment by DrSleep** [comment]
please refer to this https://github.com/DrSleep/tensorflow-deeplab-resnet#using-your-dataset
