### ISSUE TITLE
txt file issue

### ISSUE THREAD

**Issue by JadenLy** [DrSleep/tensorflow-deeplab-resnet#110]
Hello all,

@DrSleep 
I have been trying to train this model and I found out that my trian.txt is the problem. After reading some other threads, I believe that I am using the wrong one. The original txt file in folder /VOC2012/ImageSets/Segmentation only consists of the name of the file, but they do not contain something like SegmentationClassAug, though I have downloaded this file and uploaded. 

So I wonder where does this txt file come? The SegmentationClassAug.zip does not contain any txt file and original VOC2012 zip only has txt files with names of the file. Can anyone provide me with a link to get this file or I have to write a python file to convert them? 

Thanks!

**Comment by JadenLy** [comment]
Another problem is that how to correctly understand the value of mIoU. I am doing a comparison between this model and another one. The other model outputs using mAP. So is there a way to help me understand how to compare the results? 

Thanks!

**Comment by rohanksaxena** [comment]
Hello @JadenLy! I am facing the same issue, I am not able to find the train)aug.txt file which is supposed to be in SemanticClassAug.zip. Were you able to find this text file? If yes, can you please share it with me? Thanks!
