### ISSUE TITLE
Error in the concat function in kaffe.tensorflow.network

### ISSUE THREAD

**Issue by wuchichung** [DrSleep/tensorflow-deeplab-resnet#113]
As I want to implement the dense connected mechanism in deeplab, I found a possible error in kaffe.tensorflow.network, concat_dim's concat function:

@layer
    def concat(self, inputs, axis, name):
        return tf.concat(**concat_dim**=axis, values=inputs, name=name)

I think axis should be used instead of concat_dim.

**Comment by DrSleep** [comment]
it is coming from previous versions of tensorflow.
