### ISSUE TITLE
Improve results with a different dataset (fine_tune) 

### ISSUE THREAD

**Issue by isadoramsouza** [DrSleep/tensorflow-deeplab-resnet#115]
I trained the model (deeplab_resnet_init) with PASCAL VOC and only changed the number of classes to 2 (binary segmentation). Tested on my own dataset ang got mIoU = 0.69. How can I improve the results? 
I am thinking to run fine_tune.py with a different dataset but keep the number of classes (2). Is necessary to change something in the code?

**Comment by DrSleep** [comment]
refer to https://github.com/DrSleep/tensorflow-deeplab-resnet#using-your-dataset

**Comment by sunbin1205** [comment]
@isadoramsouza  你的数据集是自己制作的吗？？怎样将训练好的模型运用到自己的数据集上具体需要修改的地方，能具体说一下吗？我也是只要分割出两个类，建筑物数据集的分割！谢谢！
Is your dataset made by yourself?? How to apply the training model to the specific needs of your data set, can you elaborate on it? I also want to divide two classes only, the partition of building data set! Thank you very much!
