### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by xzha8059** [DrSleep/tensorflow-deeplab-resnet#117]
Hi, guys, how can I find the path /where/to/save/numpy/weights?

**Comment by xzha8059** [comment]
Could you provide me more details about how to convert from caffe to tensorflow? Thanks.

**Comment by DrSleep** [comment]
/where/to/save/numpy/weights is the file where your numpy weights will be saved. You define it yourself. 

For more details refer to this paragraph: https://github.com/DrSleep/tensorflow-deeplab-resnet#caffe-to-tensorflow-conversion and this repository: https://github.com/ethereon/caffe-tensorflow
