### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by boyurmit** [DrSleep/tensorflow-deeplab-resnet#118]
The parameter 'basestring' in 'tensorflow-deeplab-resnet\kaffe\tensorflow\network.py' line 78 is not defined. Is this a bug?

**Comment by xzha8059** [comment]
Yeah, I had the same problem. But I don't know how to solve it.

**Comment by boyurmit** [comment]
Already know why this issue. This code is for python2. In python3, 'str' should be used instead of 'basestring'
