### ISSUE TITLE
question about deeplab_resnet_init.ckpt

### ISSUE THREAD

**Issue by likebullet86** [DrSleep/tensorflow-deeplab-resnet#120]
i have question about deeplab_resnet_init.ckpt

in original repo provide 3 init model. 
(vgg16_128.caffemodel, vgg16_20M.caffemodel, vgg16_20M_coco.caffemodel)
 -http://liangchiehchen.com/projects/Init%20Models.html

what is the init model is same with deeplab_resnet_init.ckpt?
and how to train init mode?
 - in official said , use modified VGG-16 network to imagnet data.
 - i want to know about detail of modefied vgg-16 network

**Comment by DrSleep** [comment]
This is DeepLab-ResNet. It is a modification of ResNet-101.
