### ISSUE TITLE
Different Image Size

### ISSUE THREAD

**Issue by Fab1900** [DrSleep/tensorflow-deeplab-resnet#122]
Hey,
I would like to know if it is also possible to train my dataset with images of different size? In total there are about 1000 Images and 3 different sizes (but similiar).
Do I have to make "None" then to the attributes image_size? Do I have to be careful then with putting images of different size in one batch?

**Comment by DrSleep** [comment]
I am not aware of how to put images of different size into one batch. One batch usually assumes that you have a tensor of size (B, H, W, C), which implies that H, W are fixed
