### ISSUE TITLE
where can I download the augmented PASCAL VOC 2012 dataset from?

### ISSUE THREAD

**Issue by fanser** [DrSleep/tensorflow-deeplab-resnet#128]
Sorry to ask the stupid question. I have a benchmark with 8497 train images and 2857 evaluation images, and not 10582 and 1449 for train and val. It's troubled me. So can you give me the link to download the augmented dataset you are using.

**Comment by DrSleep** [comment]
There is a link provided in Readme: https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0
