### ISSUE TITLE
tf.contrib.metrics.streaming_mean_iou（pred，gt）is error，this is why？

### ISSUE THREAD

**Issue by zhanhuanli** [DrSleep/tensorflow-deeplab-resnet#130]
Error：tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [`labels` out of bound] [Condition x < y did not hold element-wise:x (mean_iou/confusion_matrix/control_dependency:0) = ] [0 0 0...] [y (mean_iou/ToInt64_2:0) = ] [21]

**Comment by zhanhuanli** [comment]
evaluate.py   code：
mIoU,update_op = tf.contrib.metrics.streaming_mean_iou(pred, pred, num_classes=args.num_classes,weights=weights)
.....
sess.run（update_op ）


error！！

**Comment by mohuamuyu** [comment]
This is caused by different vesion of tensorflow， this problem happens in tensorflow 1.3.0， but tensorflow 1.1.0 do not have this problem. so change the code:

change the follow code:
`  # mIoU
    pred = tf.reshape(pred, [-1,])
    gt = tf.reshape(label_batch, [-1,])
    weights = tf.cast(tf.less_equal(gt, args.num_classes - 1), tf.int32) # Ignoring all labels greater than or equal to n_classes.
    mIoU, update_op = tf.contrib.metrics.streaming_mean_iou(pred, gt, num_classes=args.num_classes, weights=weights)`

to:

`pred = tf.reshape(pred, [-1,])
	gt = tf.reshape(mask_batch, [-1,])
	indices = tf.squeeze(tf.where(tf.less_equal(gt, NUM_CLASSES - 1)), 1) ## ignore all labels >= num_classes
	gt = tf.cast(tf.gather(gt, indices), tf.int32)
	pred = tf.gather(pred, indices)
	mIoU, update_op = tf.contrib.metrics.streaming_mean_iou(pred, gt, num_classes=NUM_CLASSES)`

**Comment by mohuamuyu** [comment]
This problem may caused by different vesion of tensorflow， this problem happens in tensorflow 1.3.0， but tensorflow 1.1.0 do not have this problem. so change the code:

change the follow code:
`pred = tf.reshape(pred, [-1,])`
`gt = tf.reshape(label_batch, [-1,])`
`weights = tf.cast(tf.less_equal(gt, args.num_classes - 1), tf.int32) # Ignoring all labels greater than or equal to n_classes.`
`mIoU, update_op = tf.contrib.metrics.streaming_mean_iou(pred, gt, num_classes=args.num_classes, weights=weights)`

to:
	`pred = tf.reshape(pred, [-1,])`
	`gt = tf.reshape(mask_batch, [-1,])`
	`indices = tf.squeeze(tf.where(tf.less_equal(gt, NUM_CLASSES - 1)), 1) ## ignore all labels >= num_classes`
	`gt = tf.cast(tf.gather(gt, indices), tf.int32)`
	`pred = tf.gather(pred, indices)`
	`mIoU, update_op = tf.contrib.metrics.streaming_mean_iou(pred, gt, num_classes=NUM_CLASSES)`

**Comment by DrSleep** [comment]
exactly the same issue: https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/107

**Comment by NanqingD** [comment]
@zhanhuanli @mohuamuyu Do you know why it is written as ` <= NUM_CLASSES - 1` (20), while I think the class 21 is TV, class 0 is background.

`weights = tf.cast(tf.less_equal(gt, args.num_classes - 1), tf.int32) # Ignoring all labels greater than or equal to n_classes.`
