### ISSUE TITLE
Exporting the checkpoint file

### ISSUE THREAD

**Issue by Zumbalamambo** [DrSleep/tensorflow-deeplab-resnet#131]
How do I export the checkpoint file to pb graph for inference?

**Comment by DrSleep** [comment]
no idea. please consult official tensorflow resources for that.

**Comment by noumanriazkhan** [comment]
You can use this script:
https://github.com/KleinYuan/tf-segmentation/blob/master/tools/graph_freezer.py
Change the output_node_name if needed.
