### ISSUE TITLE
Issues about validation dataset and test dataset

### ISSUE THREAD

**Issue by yanghgai** [DrSleep/tensorflow-deeplab-resnet#133]
In 'SegmentationClassAug' you provided , the label images  have white edge which are ignored in training and evaluate process  。In DEEPLABV2 paper ,did the author also use the same SegmentationClassAug with you ? And ,can you provide the test dataset ? I don't have a institutional email address, so I can't  register a an account at PASCAL VOC Challenge performance evaluation and download server . Thanks!

**Comment by DrSleep** [comment]
the custom setup is to ignore pixels belonging to that class.
