### ISSUE TITLE
what does deep_resnet_init.ckpt come from

### ISSUE THREAD

**Issue by heryms** [DrSleep/tensorflow-deeplab-resnet#137]
I wonder is deep_resnet_init.ckpt file trained from imagenet?

**Comment by GZHermit** [comment]
yes

**Comment by yanghgai** [comment]
NO ,It is trained from COCO

**Comment by DrSleep** [comment]
from [this](http://liangchiehchen.com/projects/DeepLabv2_resnet.html) page:

> Note that the provided init.caffemodel has already been pretrained on MS-COCO.
