### ISSUE TITLE
anyway to get the class specific prediction?

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-resnet#14]

**Comment by gaopeng-eugene** [comment]
In the evaluation code, how can we get class specific accuracy rather the average?

**Comment by DrSleep** [comment]
Yes, it is possible. All you need is to acquire the confusion matrix (which is a TF local variable) and repeat the same computations as [here](https://github.com/tensorflow/tensorflow/blob/64edd34ce69b4a8033af5d217cb8894105297d8a/tensorflow/python/ops/metrics_impl.py#L794) without the reduce_mean op.
This has also been asked on StackOverflow: http://stackoverflow.com/questions/40340728/tensorflow-how-can-i-get-the-total-cm-in-tf-contrib-metrics-streaming-mean-iou

I don't have the relevant code at the moment, so if you have hard time getting predictions per class, let me know and I will look at it later.
