### ISSUE TITLE
Cannot download the pretrained model

### ISSUE THREAD

**Issue by mokii** [DrSleep/tensorflow-deeplab-resnet#148]
The link https://drive.google.com/open?id=0B_rootXHuswsZ0E4Mjh1ZU5xZVU
shows "Could not connect: Connection refused."
Does anyone have the same problem as me?

**Comment by salehjg** [comment]
the link is ok
it probably has something to do with your internet connection(try to change your IP)

**Comment by DrSleep** [comment]
seems to work fine for me; you can try to download from dropbox as well: https://www.dropbox.com/s/cd0drt6t9q1mwg0/deeplab_resnet.ckpt?dl=1
