### ISSUE TITLE
py_func: list out of range

### ISSUE THREAD

**Issue by SharonZhu** [DrSleep/tensorflow-deeplab-resnet#151]
When I started to run train.py, an error occurred:
UnknownError (see above for traceback): IndexError: list index out of range
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_UINT8, DT_INT32, DT_INT32], Tout=[DT_UINT8], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch:1, PyFunc_1/input_1, PyFunc_1/input_2)]]

It seemed that the py_func used in summary part has some problems. Could someone help me handle it? Thanks a lot.

**Comment by salehjg** [comment]
what version of tensorflow are you using?
how about python?
in case of python3 and TF 1.3 (i am not sure about the exact version of TF), try this pull request:
https://github.com/DrSleep/tensorflow-deeplab-resnet/pull/140
https://github.com/salehjg/tensorflow-deeplab-resnet

**Comment by DrSleep** [comment]
where does that occur exactly? more information would be helpful

**Comment by yuchuochuo1023** [comment]
Hi,

I just met the similar problem. It occurs when I change to use my own dataset, which I have already processed following the instruction. The error is : (there are 47 categories in my new dataset)
UnknownError (see above for traceback): exceptions.IndexError: list index out of range
         [[Node: PyFunc_1 = PyFunc[Tin=[DT_UINT8, DT_INT32, DT_INT32], Tout=[DT_UINT8], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch:1, PyFunc_1/input_1, PyFunc_1/input_2)]]

Here is the setting: 
IMG_MEAN = np.array((225.0, 225.0, 225.0), dtype=np.float32)
BATCH_SIZE = 10
DATA_DIRECTORY = '/import/data/Segmentation/train/image/'
DATA_LIST_PATH = './dataset/train_cartoon.txt'
IGNORE_LABEL = 255
INPUT_SIZE = '750,750'
LEARNING_RATE = 2.5e-4
MOMENTUM = 0.9
NUM_CLASSES = 47
NUM_STEPS = 20001
POWER = 0.9
RANDOM_SEED = 1234
RESTORE_FROM = './checkpoints/deeplab_resnet.ckpt'
SAVE_NUM_IMAGES = 2
SAVE_PRED_EVERY = 1000
SNAPSHOT_DIR = './snapshots/'
WEIGHT_DECAY = 0.0005

Do you have any idea about this problem? Thank you for your potential help!

**Comment by yuchuochuo1023** [comment]
@DrSleep

**Comment by Kimyoonkyoung** [comment]
I just met the similar problem. I think it's occur when using different num of class dataset.. I'm using 32 categories in my dataset. I suspect there is a problem with importing the pre-trained model(resnet-101), but I do not know how to solve it. @DrSleep

**Comment by Kimyoonkyoung** [comment]
**Oh! I solved it!** @SharonZhu @yuchuochuo1023 

> I was wrongly predicting.
>> The pre-trained model(resnet-101) is not problem
>> The model does not include the fc layer.

---
In the error log..
![Uploading 스크린샷 2018-02-27 오후 6.56.11.png…]()

**Comment by DrSleep** [comment]
which is written in README, if you read it carefully: https://github.com/DrSleep/tensorflow-deeplab-resnet#using-your-dataset
