### ISSUE TITLE
How to change resnet101 to resnet 152?Thank you 

### ISSUE THREAD

**Issue by DragonZzzz** [DrSleep/tensorflow-deeplab-resnet#152]
I want to change resnet 101 to resnet 152 in the deeplab net to get better features.  how to achieve it?  @DrSleep

**Comment by DrSleep** [comment]
there is no available DeepLab with ResNet-152 as far as I am aware. What you would need to do is to train it yourself.
You can find available pre-trained ResNet-152 for TensorFlow and then modify it accordingly as in ResNet-101 (i.e., remove last two pooling layers, add dilations in the last two blocks, and add ASPP-head). After that, you need to fine-tune your network for segmentation, e.g. using train.py or train_msc.py from this repository
