### ISSUE TITLE
Evaluete

### ISSUE THREAD

**Issue by felipecicero** [DrSleep/tensorflow-deeplab-resnet#154]
Dear @DrSleep , I'm working with your network on a project and I'm having problems with the size of the set for validation in evaluate.py, the script can not iterate over all the validation files and I'm not able to test all the images in my set validation. I'm using a TITAN X and I can not run more than 10 validation images.

Should not the script be iterating over all files described in "val.txt" in multiple steps instead of just the first step?

**Comment by DrSleep** [comment]
it does iterate one by one; the effective batch during evaluation is 1
