### ISSUE TITLE
In train.py how to do validation as well as training

### ISSUE THREAD

**Issue by mokii** [DrSleep/tensorflow-deeplab-resnet#157]
I want to do validation every 1000 iters to select the model. 
But in the train.py code, the data is feed into the model when initializing the model
` net = DeepLabResNetModel({'data': image_batch}, is_training=args.is_training, num_classes=args.num_classes)`
Does this mean I have to build a model to feed the training data and reload the newest parameters to build another model to feed my val data?
Is it possible to ues only one model or is there some idea more efficient.

**Comment by DrSleep** [comment]
You do not need to reload new parameters, but you will need to build
another copy of the model with `tf.variable_scope('', reuse=True)'. After
that, you analogously feed the validation batch into this copy (do not
forget to set is_training to False here).

**Comment by mokii** [comment]
@DrSleep Thank you very much. Helped me a lot!
