### ISSUE TITLE
Data augmentation by random scaling and random mirroring

### ISSUE THREAD

**Issue by siinem** [DrSleep/tensorflow-deeplab-resnet#160]
Hi to all !
Might you have information on by the random scaling and random mirroring functions at ImageReader.py, in which amount are we augmenting the training data?

I mean if i have a training set with 600 images, and if i run the fine_tune.py --random-scale --random-mirror command, how many training images will i have in the end? 

1. will there be any augmentation, so the training set will be more than 600 images or 
2. the current 600 images will be just randomly transformed so will i still have 600 images in the end but with transformed versions?

thanks in advance,
s.

**Comment by DrSleep** [comment]
In the end, your training set will still contain 600 images, but each time the network runs it will see a slight variation of any of those 600 images as augmentations are performed on the fly (thus, one can say that the number of training examples is more than 600)

**Comment by siinem** [comment]
@DrSleep Thanks a lot for your reply. So probably it is not possible to compute an exact number on to which number the training images are augmented to? 

If the batch size was 600 and the network runs for 20K iterations, could we say that total number of training images upgrades to 12000K (600*20K) images (since at every iteration images changes in some variation)?

**Comment by siinem** [comment]
Dear @DrSleep, thanks for your reply. I guess that 2NS*C should be 2*S*C, shouldn't it?
