### ISSUE TITLE
About CRF implementation

### ISSUE THREAD

**Issue by siinem** [DrSleep/tensorflow-deeplab-resnet#161]
Hi to all,
When i add the CRF implementation as a postprocessing step into the file of evaluate.py, i get a warning of 
utils.py:150: RuntimeWarning: divide by zero encountered in log  U = -np.log(probs)  # Unary potential.

I used the CRF code published here: https://github.com/DrSleep/tensorflow-deeplab-resnet/tree/crf

Is there anybody getting the same warning? and do you think this may effect the accuracy of the process?

**Comment by DrSleep** [comment]
the CRF code is based on this repository: https://github.com/lucasb-eyer/pydensecrf; please refer to it
