### ISSUE TITLE
error about train.py

### ISSUE THREAD

**Issue by sunbin1205** [DrSleep/tensorflow-deeplab-resnet#162]
run train.py met error:

E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 6021 (compatibility version 6000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
Aborted (core dumped)

Which version of cuda should be used for tensorflow0.12?

**Comment by DrSleep** [comment]
you'd better look for the answer on the official tensorflow resources.
the error you are getting explicitly stating that you are using CuDNN6.0 and your tensorflow was compiled using CuDNN5.1
