### ISSUE TITLE
Which features are being implemented

### ISSUE THREAD

**Issue by eypros** [DrSleep/tensorflow-deeplab-resnet#167]
I would like to ask  of the exact model that it is being implemented. In your repository you state that you have reimplemented [DeepLabv2](http://liangchiehchen.com/projects/DeepLabv2_resnet.html).

There it states that 3 features are included in DeepLabv2:
(1) re-purposed ResNet-101 for semantic segmentation by atrous convolution, 
(2) multi-scale inputs with max-pooling to merge the results from all scales, and 
(3) atrous spatial pyramid pooling.

Are those implemented all in tensorflow version? From my understanding:
(1) is implemented in all cases (as a core feature to semantically segment images)
(2) is implemented in train_msc.py file for example where explicitly multi scale inputs are being used. But what about (3). Is it different than (2)? From the paper they both seem quite similar to me. Is there any difference between them?

For example in the paper it states: 

> We extract DCNN score maps from multiple (three
in our experiments) rescaled versions of the original image
using parallel DCNN branches that share the same parameters. To produce the final result, we bilinearly interpolate
the feature maps from the parallel DCNN branches to the
original image resolution and fuse them, by taking at each
position the maximum response across the different scales.

which kind of resembles (2)? **maximum response** is max pooling right? So?

**Comment by DrSleep** [comment]
maximum response is max pooling.
ASPP is a multi-branch convolutional block with different dilation rates. It is implemented, take a look at the model definition.
