### ISSUE TITLE
the code didn't support multi GPU?

### ISSUE THREAD

**Issue by shipeng-uestc** [DrSleep/tensorflow-deeplab-resnet#170]
Hi,I have one error.
On one GPU,I can use batch=4  to train my own dataset
But, When using 2 GPUs , I can't use batch=8 to train and it will occure 'Out of memory'.

**Comment by DrSleep** [comment]
No, it does not. You can easily modify it. This might be helpful: https://github.com/vahidk/EffectiveTensorflow#multi_gpu
