### ISSUE TITLE
Running out of memory when doing evaluation on own dataset

### ISSUE THREAD

**Issue by jsinge97** [DrSleep/tensorflow-deeplab-resnet#183]
How can I do evaluation in batches as my gpu is running out of memory when I do evaluation?

**Comment by DrSleep** [comment]
if your images are of the same size, you can do the same way as done in train by dequeuing the batch of images: https://github.com/DrSleep/tensorflow-deeplab-resnet/blob/master/train_msc.py#L144

Otherwise, you would need to manually design a way of batching images with different sizes
