### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by weixia1** [DrSleep/tensorflow-deeplab-resnet#188]
hi , i now using your code to evaluation ,
but something is wrong ,can you help me ,thank you

> InvalidArgumentError (see above for traceback): assertion failed: [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (mean_iou/confusion_matrix/control_dependency:0) = ] [0 0 0...] [y (mean_iou/ToInt64_2:0) = ] [21]

**Comment by zhenmafan7** [comment]
> hi , i now using your code to evaluation ,
> but something is wrong ,can you help me ,thank you
> 
> > InvalidArgumentError (see above for traceback): assertion failed: [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (mean_iou/confusion_matrix/control_dependency:0) = ] [0 0 0...] [y (mean_iou/ToInt64_2:0) = ] [21]

When running the evaluate.py, I also encountered this problem.Do you have resolved this problem?

**Comment by weixia1** [comment]
@zhenmafan7 oh, it have been a long time, i forgot detail,  maybe **NUM_CLASSES** (the number of labels) in train code is not equal to **NUM_CLASSES**  in evaluate code. For example, you use **NUM_CLASSES**=20 in traning, but defined **NUM_CLASSES**=21 in evaluate

**Comment by zhenmafan7** [comment]
@weixia1 thanks for your reply,I alredy sloved it, the problem ocuured just because the version of tensorflow is difference.
And thank you again!
