### ISSUE TITLE
What's difference from deeplab_resnet_init.ckpt and deeplab_resnet.ckpt ?

### ISSUE THREAD

**Issue by yishishiyi** [DrSleep/tensorflow-deeplab-resnet#195]
Is deeplab_resnet_init.ckpt pretrained from MS COCO as described in http://liangchiehchen.com/projects/DeepLabv2_resnet.html ? 

Is deeplab_resnet.ckpt the final model trained/validated on VOC 2012 Aug dataset ?

**Comment by zhouyuan888888** [comment]
I have the same question,now have you ever understood the differences between deeplab_resnet.cktp and deeplab_resnet_init.ckpt?is deeplab_resnet.ckpt the final model? thank you very much.

**Comment by zhouyuan888888** [comment]
@yishishiyi

**Comment by DrSleep** [comment]
as explained in README: https://github.com/DrSleep/tensorflow-deeplab-resnet#caffe-to-tensorflow-conversion;

resnet.ckpt - trained on PASCAL VOC, init - pre-trained on MS COCO with last layers initialised randomly.

**Comment by zhouyuan888888** [comment]
@DrSleep thank you so much~0**__**0,thank you!!!!!!
