### ISSUE TITLE
Where can i find pretrained Imagenet model?

### ISSUE THREAD

**Issue by TheDog223** [DrSleep/tensorflow-deeplab-resnet#199]
I want to train my model with checkpoint the aforementioned model. Anyone know where should i download it from?  @arslan-chaudhry  @DrSleep  
When i try to load resnet_101_v2  pretrained model  i get  the following error:

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Tensor name "bn2a_branch1/beta" not found in checkpoint files ./snapshots2/resnet_v2_101.ckpt
     [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]

     [Node: save_1/RestoreV2/_225 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_230_save_1/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]

**Comment by DrSleep** [comment]
you can try to convert caffe to tf as described here: https://github.com/DrSleep/tensorflow-deeplab-resnet#caffe-to-tensorflow-conversion
