### ISSUE TITLE
Do you update the google drive model?

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-resnet#20]
the old model can not work on the current code. deeplab_init_bn.ckpt and deeplab_pretrained_bn.ckpt. What is the differece between the current google drive code and original one?

**Comment by DrSleep** [comment]
Yes, the code and the link were updated last week. 
The difference in model files lies in how the batch norm layer parameters are called: for example, previous 'conv1/BatchNorm/beta' is now 'conv1/beta'.

From readme:

> 
> Updates
> 
> 29 Jan, 2017:
> 
> Fixed the implementation of the batch normalisation layer: it now supports both the training and inference steps. If the flag --is-training is provided, the running means and variances will be updated; otherwise, they will be kept intact. The .ckpt files have been updated accordingly - to download please refer to the new link provided below.
> Image summaries during the training process can now be seen using TensorBoard.
> Fixed the evaluation procedure: the 'void' label (255) is now correctly ignored. As a result, the performance score on the validation set has increased to 80.1%.
> 
>

**Comment by gaopeng-eugene** [comment]
how can you change the name of parameters? Just out of curiosity.

**Comment by gaopeng-eugene** [comment]
when i use deeplab_resnet.ckpt, the following error come out.

NotFoundError (see above for traceback): Tensor name "bn2a_branch2a/moving_mean" not found in checkpoint files ./deeplab_resnet.ckpt

tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "bn2a_branch2a/moving_mean" not found in checkpoint files ./deeplab_resnet.ckpt

**Comment by gaopeng-eugene** [comment]
deeplab_resnet_init.ckpt works well.

**Comment by DrSleep** [comment]
If you are initialising them, you can just change the name of the scope where they are defined.
If you have variables named differently than the ones in your checkpoint, you can pass the dictionary as the var_list variable to your Saver definition: the keys of the dictionary will be the original names from the checkpoint file and the values are corresponding current variables. Then to save your current variables with new names you wound need another Saver with var_list simply being the list of these variables.

As for the error, I cannot reproduce it. Please check that you have downloaded the new file.
