### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by nelsonrproenza** [DrSleep/tensorflow-deeplab-resnet#206]
Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized

This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results.

How could I ensure that only a single OpenMP runtime is linked into the process?

**Comment by DrSleep** [comment]
no idea, cannot help with that - the issue is more general and not related to the code per se.
