### ISSUE TITLE
evaluation score should be got from reduced_val.txt rather than val.txt

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-resnet#22]
There is a overlap between val.txt and augmented_train.txt. That's the reason we should run evaluation on reduced_val.txt.

https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/data/pascal/seg11valid.txt

**Comment by DrSleep** [comment]
@gaopeng-eugene, for example, [this simple code](https://gist.github.com/DrSleep/177c497a0c7761d58a8de38fd8fb16aa) shows that there is no overlap between the two lists in this repository.

**Comment by DrSleep** [comment]
I have added the `val_reduced.txt` to the `dataset/` folder for evaluation.
