### ISSUE TITLE
Augmented dataset.

### ISSUE THREAD

**Issue by warmspringwinds** [DrSleep/tensorflow-deeplab-resnet#3]
Hi.

Thank you for your repository!

I have a small question: where did you get the augmented dataset from?

**Comment by DrSleep** [comment]
Hi, I did it long time ago relying on this FAQ by the DeepLab team: http://ccvl.stat.ucla.edu/deeplab_faq/
Now it seems that the link provided to the dataset with extra annotations is broken. I will try to find an alternative link.

**Comment by gaopeng-eugene** [comment]
https://github.com/martinkersner/train-DeepLab

This GitHub branch provide the scripts on how to build the augmented dataset

**Comment by DrSleep** [comment]
76.5% is the result of the converted to TF model (the link to the model file is provided in README).

**Comment by DrSleep** [comment]
Please refer to this: http://home.bharathh.info/pubs/codes/SBD/download.html
#https://github.com/daijifeng001/MNC/issues/3

**Comment by nicolov** [comment]
Thanks. Note that the segmentation labels are currently distributed as .mat files. PR #4  adds a simple script to generate images that can be used with the current trainer.

**Comment by gaopeng-eugene** [comment]
Can you tell me the mAP if the model is trained from scratch?

**Comment by DrSleep** [comment]
Unfortunately, I cannot tell you that. PRs are always welcome.
