### ISSUE TITLE
can you provide some suggestions on how to install tensorlfow 0.12

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-resnet#32]
right now, the compiled tensorlfow 0.12 version has been removed from homepage. Do you have any suggestion on how to install the 0.12 version? I am using docker right now which means I need to reinstall 0.12 every time when I set up a container.

**Comment by DrSleep** [comment]
Tensorflow is now available for installation using pip, so you can run
something like pip install tensorflow==0.12.1

**Comment by gaopeng-eugene** [comment]
thank you for your response. But your method can only download the cpu version. How can I download the GPU version.

**Comment by gaopeng-eugene** [comment]
problem solved by adding pip install tensorflow-gpu==0.12.0
