### ISSUE TITLE
About the evaluate.py

### ISSUE THREAD

**Issue by Fansiee** [DrSleep/tensorflow-deeplab-resnet#36]
After I train my model, and get the snapshots, I want to evaluate the final model.
However, it doesn't work. I met this issue: http://stackoverflow.com/questions/41048819/how-to-restore-a-model-by-filename-in-tensorflow-r12

And I fix it by using the answer:

import tensorflow as tf
from tensorflow.core.protobuf import saver_pb2
...
saver = tf.train.Saver(write_version = saver_pb2.SaverDef.V1)
saver.save(sess, './model.ckpt', global_step = step)

It perhaps the evaluate.py doesn't fit the new saver.

Could you fix it?

Thanks

**Comment by DrSleep** [comment]
Hi, would you please post how you call the evaluation script in the first place?
In the issue that you have linked, the command is '..model.ckpt-data...'; if you just run '..model.ckpt' instead, everything should work fine in the first place.

**Comment by Fansiee** [comment]
I have the same problem as in the link.
In my snapshots, I only have model.ckpt-3000.data-00000-of-000001, model.ckpt-3000.index, and model.ckpt-3000.meta files. There are no '...model.ckpt' in the snapshots.
And in the evaluate.py, the RESTORE_FROM is './deeplab_resnet.ckpt'.
I don't know which file is the correct in the place.
I tried the three types, but I get the same problem in the link.

Could you place tell me what's the correct thing in the RESTORE_FROM?

**Comment by DrSleep** [comment]
When you run the code with '--restore-from ./model.ckpt-3000', even though
there are no 'model.ckpt-3000', the TF interface would be able to fetch the
right file and restore the weights.

**Comment by Fansiee** [comment]
Oh, My!
It works! Thanks very much！
