### ISSUE TITLE
Extending the model

### ISSUE THREAD

**Issue by arslan-chaudhry** [DrSleep/tensorflow-deeplab-resnet#46]
@DrSleep I am trying to extend the model to add distillation loss in addition to cross entropy with ground truth labels. Something like: 
```
loss = cross_entropy(predictions, gt) + cross_entropy(predictions, activations_from_earlier_model)
```
I have everything covered except for the input pipeline. Right now, I have stored activations from an earlier model in an .npz file, where each activation is of size [H_ x W_ x n_classes] (down-sampled activations). I have added a new **data_list** of the following form:
```
/path/to/image_1.jpg /path/to/mask_1.png /path/to/activation_1.npz
/path/to/image_2.jpg /path/to/mask_2.png /path/to/activation_2.npz
.
.
```
The problem with the above is I don't know of any **reader** in tensorflow that matches **npz** file format. The same goes for the decoder as well. 
Next, I tried dumping the activations in **csv** format and tried **TextLineReader** and corresponding **decode_csv** to read the data, but that does not seem to accept the outputs of tf.train.slice_input_producer, giving following error:
```
self.image, self.label, self.activation = read_images_from_disk(self.queue, self.input_size, random_scale, random_mirror)
...
activation_reader = tf.TextLineReader()
key, activation_contents = activation_reader.read(input_queue[2])
...
TypeError: Input 'queue_handle' of 'ReaderRead' Op requires l-value input
```
I think I could instead use something like this:
```
self.image_list, self.label_list, self.actv_list = read_labeled_image_list(self.data_dir, self.actv_dir, self.data_list)
self.queue[0] = tf.train.string_input_producer(self.images_list, shuffle=input_size is not None, seed='123')
self.queue[1] = tf.train.string_input_producer(self.label_list, shuffle=input_size is not None, seed='123')
self.queue[2] = tf.train.string_input_producer(self.actv_list, shuffle=input_size is not None, seed='123')
self.image, self.label, self.activation = read_images_from_disk(self.queue, self.input_size, random_scale, random_mirror)
```
But I am not sure. 
Is there any nicer solution to what I am trying to achieve here in tensorflow? I would prefer to use npz format because of memory constraints.

**Comment by arslan-chaudhry** [comment]
I tried writing a python wrapper around the reader:
```
def load_npz(npz_file):
    actv_arr = np.load(npz_file)
    activation = actv_arr['actv']
    return activation                                                
```
and use it to parse the queue of activations:
```
activation = tf.py_func(load_npz, [input_queue[2]], [tf.float32])
```
But, I am stuck at following out of range error:
```
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_3_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: create_inputs/batch = QueueDequeueMany[_class=["loc:@create_inputs/batch/fifo_queue"], component_types=[DT_FLOAT, DT_UINT8, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
```

I don't understand which op is depleting my activation_queue. Maybe, I haven't fully understood the use of python_wrappers in queues.

**Comment by arslan-chaudhry** [comment]
I was able to figure out the solution.

**Comment by DrSleep** [comment]
Just read it, was out for some time.
Great that you found the solution!
