### ISSUE TITLE
Does the mIoU include the the background?

### ISSUE THREAD

**Issue by fanq15** [DrSleep/tensorflow-deeplab-resnet#47]
I wonder when calculate the mIoU if it includes the background?
Does it calculate the 21-class IoU including the background and then get the mean?
Or Does it calculate the 20-class IoU excluding the background?
I have check the VOC 2012 dev toolkit, it seems like it include the background.
But I am no sure.
Could you please  help me figure it out?

**Comment by DrSleep** [comment]
It is calculated including backgroud. See, for example, the result from the evaluation server: http://host.robots.ox.ac.uk/anonymous/FIQPRH.html
