### ISSUE TITLE
tf.split()

### ISSUE THREAD

**Issue by weigq** [DrSleep/tensorflow-deeplab-resnet#49]
I run the train.py on tensoeflow 1.0.0 the following error happenes
```   
img_r, img_g, img_b = tf.split(split_dim=2, num_split=3, value=img)
TypeError: split() got an unexpected keyword argument 'split_dim'
```

what is wrong with the 'split_dim'

**Comment by corenel** [comment]
You may use TF1.0 or higher, and the API changes.

> `tf.split` now takes arguments in a reversed order and with different
  keywords. In particular, we now match NumPy order as
  `tf.split(value, num_or_size_splits, axis)`.

You should change `img_r, img_g, img_b = tf.split(split_dim=2, num_split=3, value=img)`into `img_r, img_g, img_b = tf.split(value=img, num_or_size_splits=3, axis=2)`.

I've forked a TF1.0 compatible version of this repo in [this](https://github.com/corenel/tensorflow-deeplab-resnet).

**Comment by weigq** [comment]
it works! Thank you very much! @corenel
