### ISSUE TITLE
inference.py

### ISSUE THREAD

**Issue by weigq** [DrSleep/tensorflow-deeplab-resnet#51]
I have trained the net, and when I run the`inference.py`, I got this error 👍
```
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for deeplab_resnet_init.ckpt

```

anyone can help  me?

**Comment by DrSleep** [comment]
You should change the `restore-from` flag to point to an existing ckpt file
