### ISSUE TITLE
Where to download augmented PASCAL VOC 2012 dataset 

### ISSUE THREAD

**Issue by zhixy** [DrSleep/tensorflow-deeplab-resnet#54]
I'm sorry to ask this stupid question, but I try my best, but don't find the augmented PASCAL VOC 2012 dataset, which consists of 10582 train image. Can anybody tell me the link?

**Comment by weigq** [comment]
can you access google drive ,if so, you can down [here](https://drive.google.com/file/d/0B4ACJXPIvdmWSHRmc29QUjBtQWs/view?usp=sharing)

**Comment by zhixy** [comment]
Yes, thanks a lot!

**Comment by mokii** [comment]
There seems there is something wrong with the file above, anywhere else I can get it please? Or could I bother you send a copy to my email, 544984610@qq.com please!

**Comment by GHmaryam** [comment]
@mokii  See if changing your browser might help. Try Google Chrome!! For me Opera did not work, but Chrome did. Emailing would do a google drive download link again as the size is large for sending through email.
