### ISSUE TITLE
tensorflow 1.0

### ISSUE THREAD

**Issue by bjml** [DrSleep/tensorflow-deeplab-resnet#55]
when will it support tf1.0 ? Becaue many apis have changed and the code doesn't work now

**Comment by speedinghzl** [comment]
Hi, @bjml，I have changed the API from tf0.12 to tf1.0. You can access my fork via https://github.com/speedinghzl/tensorflow-deeplab-resnet.git

**Comment by DrSleep** [comment]
Tensorflow 1.1.0 is now supported
