### ISSUE TITLE
Restore partial weights after change input channels

### ISSUE THREAD

**Issue by j50888** [DrSleep/tensorflow-deeplab-resnet#56]
I want to add one additional channel(grey level image).
So the channel size of input changes from 3 to 4.
I want to restore the weights for the origin 3 channels.
How can I do that?

I tried to do not restore the 'conv1' weights , but it can't converge.

**Comment by DrSleep** [comment]
I have written one possible solution here: https://gist.github.com/DrSleep/78c4e648343ba11ff32ceb2236b9f806#file-partial_restore-ipynb

Please adapt it as you wish for your case.

**Comment by j50888** [comment]
Thank you for the help!
