### ISSUE TITLE
train my own dataset

### ISSUE THREAD

**Issue by weigq** [DrSleep/tensorflow-deeplab-resnet#57]
I want to train the model on my own image dataset, what anything else I should do except for changing the    code which contains the path to image  to my own dataset image?

thanks !

**Comment by DrSleep** [comment]
For now please refer to these issues for relevant information: https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/12 and https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/40.
I plan to include the instructions to Readme soon.

**Comment by weigq** [comment]
can you update the readme ?? I want to train on my own dataset
thx

**Comment by VanitarNordic** [comment]
@DrSleep 

Please update the readme

**Comment by DrSleep** [comment]
https://github.com/DrSleep/tensorflow-deeplab-resnet#using-your-dataset

**Comment by sunbin1205** [comment]
@weigq 
Have you successfully trained your own data set? How do you make your own voc data set?
