### ISSUE TITLE
error when train on ADE20k

### ISSUE THREAD

**Issue by zhixy** [DrSleep/tensorflow-deeplab-resnet#58]
I want to train a model on ADE20k, so I modified 'DATA_DIRECTORY' and 'DATA_LIST_PATH' in 'train.py' but don't modified others. I know the there are 150 classes in ADE20k, but I just wanna have a try first.  I sufffered a wired problem as follows, saying the image cannot be found. But I'm sure the image is there. Can anybody give me a hand?
`
W tensorflow/core/framework/op_kernel.cc:993] Not found: /Storage/zhixy/ADE20k/annotations/training/ADE_train_00009635.png
W tensorflow/core/framework/op_kernel.cc:993] Not found: /Storage/zhixy/ADE20k/annotations/training/ADE_train_00009635.png
         [[Node: create_inputs/ReadFile_1 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/input_producer/Gather_1)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: /Storage/zhixy/ADE20k/annotations/training/ADE_train_00009635.png
         [[Node: create_inputs/ReadFile_1 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/input_producer/Gather_1)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: /Storage/zhixy/ADE20k/annotations/training/ADE_train_00009635.png
         [[Node: create_inputs/ReadFile_1 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/input_producer/Gather_1)]]
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    main()
  File "train.py", line 233, in main
    loss_value, images, labels, preds, summary, _ = sess.run([reduced_loss, image_batch, label_batch, pred, total_summary, train_op], feed_dict=feed_dict)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 16, current size 0)
         [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
         [[Node: Gather/_1075 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5339_Gather", tensor_type=DT_UINT8, _device="/job:l
ocalhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'create_inputs/batch', defined at:
  File "train.py", line 244, in <module>
    main()
  File "train.py", line 132, in main
    image_batch, label_batch = reader.dequeue(args.batch_size)
  File "/Storage/zhixy/speedinghzl/tensorflow-deeplab-resnet/deeplab_resnet/image_reader.py", line 180, in dequeue
    num_elements)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 872, in batch
    name=name)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 667, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1310, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/zhixy/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 16, current size 0)
         [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]
         [[Node: Gather/_1075 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5339_Gather", tensor_type=DT_UINT8, _device="/job:l
ocalhost/replica:0/task:0/gpu:0"]()]]

`

**Comment by DrSleep** [comment]
Could you please provide the value of the 'DATA_DIRECTORY' argument and the data list itself that you are using?

**Comment by zhixy** [comment]
DATA_DIRECTORY = '/Storage/zhixy/ADE20k'
DATA_LIST_PATH = './train.txt'

I don't modify the file structure of ADE20k dataset, and I generated the data list by myself, which is like:
`/images/training/ADE_train_00000001.jpg /annotations/training/ADE_train_00000001.png`

**Comment by DrSleep** [comment]
Now I haven't worked with ADE20K, but from [their website](http://groups.csail.mit.edu/vision/datasets/ADE20K//ADE20K_2016_07_26/images/training/h/hotel_room/ADE_train_00009635_seg.png) the name of the segmentation file is `ADE_train_00009635_seg.png`: check if that is indeed the case.

**Comment by zhixy** [comment]
No, I actually work on the [sub-dataset](http://sceneparsing.csail.mit.edu/) of ADE20k, I'm pretty sure the mask image is there.

**Comment by DrSleep** [comment]
Okay.
I have downloaded the sub-dataset and run the same command, and it works fine. Here is the proof:
![tb](https://cloud.githubusercontent.com/assets/7841432/24329710/1b7ed2fe-1217-11e7-9f66-c15de5fa46c0.png)


Here is my setup:

```
DATA_DIRECTORY = '/home/drsleep/Downloads/ADEChallengeData2016'
DATA_LIST_PATH = './dataset/train_ade.txt'
```
[train_ade.txt](https://github.com/DrSleep/tensorflow-deeplab-resnet/files/870624/train_ade.txt)

I would suggest to check once again that the paths are indeed correct.

**Comment by zhixy** [comment]
You really save my day! Inspired by you, I checked my data list file again, and I realize that I shouldn't use '\r\n' in my matlab script which is used to generate the data list file, I correct it to '\n', it works now.
Thank you very much!

**Comment by zhixy** [comment]
By the way, is there a way that I can use multi gpu when training? Sorry to ask this kind of problem, I'm really a newer of tensorflow.

**Comment by DrSleep** [comment]
There is no such an option at the moment.

**Comment by zhixy** [comment]
OK. I will try to implement it by myself. Anyway, really appreciate your work and your help!
