### ISSUE TITLE
Fail to inference with saved checkpoint

### ISSUE THREAD

**Issue by JoeHEZHAO** [DrSleep/tensorflow-deeplab-resnet#59]
I  modify the train.py code and train my own data. After all 200001 steps, I have checkpoint and many saved model in 'snapshots' folder. I try to do inference on single image with saved model. My command line is :

**python inference.py /home/username/testing_data/1.jpeg /home/username/tf_deeplab_resnet/snapshots/checkpoint**

However ,below error keeps coming up : 

W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file /home/zhaohe/tf_deeplab_resnet/snapshots/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "inference.py", line 100, in <module>
    main()
  File "inference.py", line 85, in main
    load(loader, sess, args.model_weights)
  File "inference.py", line 47, in load
    saver.restore(sess, ckpt_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /home/zhaohe/tf_deeplab_resnet/snapshots/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_378 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_378/tensor_names, save/RestoreV2_378/shape_and_slices)]]
	 [[Node: save/RestoreV2_378/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_3540_save/RestoreV2_378", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_378', defined at:
  File "inference.py", line 100, in <module>
    main()
  File "inference.py", line 84, in main
    loader = tf.train.Saver(var_list=restore_var)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file /home/zhaohe/tf_deeplab_resnet/snapshots/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_378 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_378/tensor_names, save/RestoreV2_378/shape_and_slices)]]
	 [[Node: save/RestoreV2_378/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_3540_save/RestoreV2_378", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Is there any suggestion on what can I do ?

Best
He Zhao

**Comment by weigq** [comment]
I want to know how do you train on your own dataset ?  i also need to do so.
thx

**Comment by weigq** [comment]
@JoeHEZHAO  
may be you should use the deeplab_resnet.ckpt  ???

**Comment by DrSleep** [comment]
@JoeHEZHAO, you must use the '.ckpt' file, not 'checkpoint'

**Comment by JoeHEZHAO** [comment]
@weigq Sure I do the following steps:
1. prepare your own dataset and change the following path and parameter to your own dataset.
DATA_DIRECTORY = '/home/VOCdevkit'
DATA_LIST_PATH = './dataset/train.txt'
INPUT_SIZE = 'your_img_height, your_img_width'

2. in the 'datasets' foler, modify train.txt file (you might want to create a new one and change DATA_LIST_PATH above to new file). Follow the existing pattern, like '/path/to/trainImg /path/to/groundtruth/', to setup your dataset.

3. Make sure your training images are RGB three channels and jpeg format. Make sure your gt images are one channel and png format.

4. According to how many classes you want to have, modify the 'n_classes' flag in train.py; Also, change the '/deeplab_resnet/model.py' as following:
      (self.feed('res5b_relu', 
                   'bn5c_branch2c')
             .add(name='res5c')
             .relu(name='res5c_relu')
             .atrous_conv(3, 3, n_classes - 1, 6, padding='SAME', relu=False, name='fc1_voc12_c0'))
       (self.feed('res5c_relu')
             .atrous_conv(3, 3, n_classes - 1, 12, padding='SAME', relu=False, name='fc1_voc12_c1'))
        (self.feed('res5c_relu')
             .atrous_conv(3, 3, n_classes - 1, 18, padding='SAME', relu=False, name='fc1_voc12_c2'))
        (self.feed('res5c_relu')
             .atrous_conv(3, 3, n_classes - 1, 24, padding='SAME', relu=False, name='fc1_voc12_c3'))

Above changing is to make your network have the right softmax classification dimensions.

5. I am pretty sure above are necessary steps. And I also think there are more things need modify, since the model I trained is not good, always high loss. Let's  keep in touch and discuss.

**Comment by JoeHEZHAO** [comment]
@weigq deeplab_resnet.ckpt are pre-trained model for 21 classes.

**Comment by JoeHEZHAO** [comment]
@DrSleep I am pretty sure the command I use is:
python inference.py /home/username/testing_data/1.jpeg /home/username/tf_deeplab_resnet/snapshots/checkpoint

There could be problem in modes save restore version.  I went through that problem last time.

**Comment by DrSleep** [comment]
Use one of your '.ckpt' files in the snaphots/ folder.

[`python inference.py /path/to/your/image /path/to/ckpt/file`](https://github.com/DrSleep/tensorflow-deeplab-resnet#inference)

**Comment by JoeHEZHAO** [comment]
@DrSleep Solved. Sorry I did not see the readMe clearly. Last time the using checkpoint is fine.

**Comment by DrSleep** [comment]
Great to hear!
