### ISSUE TITLE
About the label

### ISSUE THREAD

**Issue by daichengasda** [DrSleep/tensorflow-deeplab-resnet#65]
Hello,I found out that when  you  deal with the label data,you just use label=tf.image.decode_png(label_contents, channels=1) to convert it to a grayscale image. With this,there are many images whose pixel values are greater than 21. This causes the entire image to be used as a background，but in fact it isn't. In this case the accuracy of the evaluate is very low,I only get about 4%.I want to ask how to solve the problem.Thanks!

**Comment by daichengasda** [comment]
It maybe because I have no directory called SegmentationClassAug, where I can download it?

**Comment by j50888** [comment]
#54
