### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by j50888** [DrSleep/tensorflow-deeplab-resnet#69]
Hi,
I used the crf branch and found there was a bug.
In utils.py line 111:
`d = dcrf.DenseCRF2D(h, w, n_classes) # Define DenseCRF model.`
It should be:
`d = dcrf.DenseCRF2D(w, h, n_classes) # Define DenseCRF model.`

**Comment by DrSleep** [comment]
Thanks! Fixed
