### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by abc8350712** [DrSleep/tensorflow-deeplab-resnet#70]
I run the train.py,But it reports:
/tensorflow/core/util/tensor_slice_reader.h:168] Check failed: sss_[idx]->Get(key, &value) Failed to seek to the record for tensor res4b16_branch2b/weights, slice -:-:-:-: computed key = 
Aborted (core dumped)

How can i solve it?

**Comment by DrSleep** [comment]
First, you would need to provide what script you are running and with what configuration.
