### ISSUE TITLE
Lower mIoU

### ISSUE THREAD

**Issue by Fansiee** [DrSleep/tensorflow-deeplab-resnet#71]
I use your train.py, train on  your ./dataset/train.txt, and evaluate on your ./dataset/val.txt.
And I disn't use
BUT, I only got mIoU 0.748, which is much lower than your result.
And I experiment using  --random-mirror --random-scale, but the result is 0.749.
I use the same set as yours. 
Help~~~~

**Comment by DrSleep** [comment]
Please check that you are using the same dataset and running the scripts with the same set of parameters.
Several people reported similar to mine results. I am unable to test all possible configurations myself.

Please read this topic as well: https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/18
