### ISSUE TITLE
"Convert.py" Error

### ISSUE THREAD

**Issue by VanitarNordic** [DrSleep/tensorflow-deeplab-resnet#73]
Hello,

The DeeplabV2 has two caffemodels. one named `init.caffemodel` and the second named `train_iter_20000.caffemodel`

I tried both but I get this error: 

```
Check failed: target_blobs.size() == source_layer.blobs_size() (5 vs. 3) Incompatible number of blobs for layer bn_conv1
*** Check failure stack trace: ***
Aborted (core dumped)
```

Please consider this, or upload the Tensorflow weights somewhere. Thanks.

**Comment by DrSleep** [comment]
The link to the converted weights is provided. Please read Readme carefully
before asking questions/opening new issues.

As for your error, it might be because of your caffe version.

**Comment by VanitarNordic** [comment]
Hh sorry yes, you are right. I just missed that download link

But anyway before closing this issue, may I ask you what is the difference between the `resnet_init` weights `resnet`?

**Comment by DrSleep** [comment]
Init is the model pretrained on COCO (not on Pascal). Resnet is the init
model trained on Pascal
