### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wuchichung** [DrSleep/tensorflow-deeplab-resnet#75]
Hello, Vladimir.

I train the model for 3 classes only with following:
                     python train.py --random-mirror --random-scale --not-restore-last

and inference the model with:
                     python inference.py /path/to image/dummy.jpg  /data/snapshots/model.ckpt-5000 --num-classes=3

However, this error keep coming up:

NotFoundError (see above for traceback): Key fc1_voc12_c0/biases not found in checkpoint
	 [[Node: save/RestoreV2_417 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_417/tensor_names, save/RestoreV2_417/shape_and_slices)]]
	 [[Node: save/RestoreV2_451/_785 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_3350_save/RestoreV2_451", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by DrSleep** [comment]
Hi, thanks for the report!

There was a bug with Saver: it was saving the same variables that been restored (that is why the fc parameters could not be found). 
I have fixed the bug now, please check whether your issue is resolved (you would need to run the training script once more).

**Comment by wuchichung** [comment]
yes, this should fix the problem.
But please change the saver in train.py also. 
Thank you, Vladimir.

**Comment by wuchichung** [comment]
ok both fixed. Thank you.

**Comment by lee2430** [comment]
I've run into the same issue, and come here looking for solutions. Good work!
