### ISSUE TITLE
IOU results are not in harmony with segmentation results

### ISSUE THREAD

**Issue by VanitarNordic** [DrSleep/tensorflow-deeplab-resnet#78]
I reached an IOU on my own dataset as 0.93, which is quite fine, but the segmentation results are not as good as I had tested before with FCN-8s which is a weaker model in comparison with DeepLabV2. 

I don't get a superb result in accordance with this impressive IOU. specially if the target object is small, the model segments nothing and consider all image as background, then this high IOU value would under question.

Maybe there is something wrong inside `inference.py`

**Comment by DrSleep** [comment]
I see no issue here regarding the repo. Please double check your dataset first.
