### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'

### ISSUE THREAD

**Issue by Yaredoh** [DrSleep/tensorflow-deeplab-resnet#83]
Am using tensorflow 1.0 and python 3.6. can you check it ?

Traceback (most recent call last):
  File "train.py", line 253, in <module>
    main()
  File "train.py", line 144, in main
    net = DeepLabResNetModel({'data': image_batch}, is_training=args.is_training, num_classes=args.num_classes)
  File "/home/batuser/Documents/color/kaffe/tensorflow/network.py", line 48, in __init__
    self.setup(is_training, num_classes)
  File "/home/batuser/Documents/color/deeplab_resnet/model.py", line 114, in setup
    .atrous_conv(3, 3, 256, 2, padding='SAME', biased=False, relu=False, name='res4a_branch2b')
  File "/home/batuser/Documents/color/kaffe/tensorflow/network.py", line 22, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/batuser/Documents/color/kaffe/tensorflow/network.py", line 170, in atrous_conv
    kernel = self.make_var('weights', shape=[k_h, k_w, c_i / group, c_o])
TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'

**Comment by cbessega** [comment]
I had the same problem. You will need to do a bunch of small tweaks to make it work in Python 3.6. 
In case you are not especially interested in Python 3.6, the repo runs perfectly fine in 2.7

In that particular case what happens is that get_shape() in a couple of places of kaffe/tensorflow/network.py  returns a dimension, you should use get_shape().value

To get the shape as a list of ints, do tensor.get_shape().as_list()

**Comment by Yaredoh** [comment]
Thanks, @cbessega I will check it on 2.7.

**Comment by NitishMutha** [comment]
Hi, @cbessega, @DrSleep  can you let me know what all fixes would be required to make it compatible with 3.6?
Since i am on windows machine, tensorflow on windows just supports python >= 3.5, so i would have to make those fixes to make it work on my machine.

**Comment by YemanBrhane** [comment]
type casting the Dimension to int will solve the problem: if you have a=10, dim = X.shape[10], then instead of a*dim use a*int(dim)

**Comment by fastlater** [comment]
@YemanBrhane Sorry but I am newbie in python.
How do you change the original code line:
kernel = self.make_var('weights', shape=[k_h, k_w, c_i / group, c_o])
so if can be executed in python3.

**Comment by fastlater** [comment]
For newbies (like me) and as mentioned in https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/80
from line: 
`kernel = self.make_var('weights', shape=[k_h, k_w, c_i / group, c_o])`
change it to:
`kernel = self.make_var('weights', shape=[k_h, k_w, int(c_i) / group, c_o])`

**Comment by dwleeKAIST** [comment]
sz = input.shape
sz[0]  :  Dimension type.
You need to use typecasting by  ' int(sz[0]) '.

**Comment by kourouklides** [comment]
FYI I had exactly the same error when running the [Transformer tutorial](https://www.tensorflow.org/tutorials/text/transformer) and I managed to resolve it by adding `.numpy()` at the end, i.e. `temp_learning_rate_schedule(tf.range(40000, dtype=np.float32)).numpy()`
