### ISSUE TITLE
Is there any improvement for test accuracy on Pascal VOC Recently

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-resnet#87]

**Comment by DrSleep** [comment]
In general, yes: check out recent [DeepLab v3 paper](https://arxiv.org/abs/1706.05587) and [this guide](http://blog.qure.ai/notes/semantic-segmentation-deep-learning-review)

**Comment by amiltonwong** [comment]
BTW, @gaopeng-eugene , @DrSleep ,
Would you have interest to implement DeepLab v3?
