### ISSUE TITLE
how to add Dice coefficient in evaluate.py

### ISSUE THREAD

**Issue by daobinhuang** [DrSleep/tensorflow-deeplab-resnet#91]
Hi @DrSleep:
I note that in evaluate.py, you use the function "streaming_mean_iou" to calculate the miou, I want to calculate the dice coefficient ,  How can I add some code in evaluate.py to do it ?  there is some function like  "streaming_mean_iou"  that can be called directly? thanks !

**Comment by DrSleep** [comment]
I am not aware of such a function. Sorry, cannot help with this one
