### ISSUE TITLE
Why I get only 0.047 evaluation mIoU on VOC

### ISSUE THREAD

**Issue by mokii** [DrSleep/tensorflow-deeplab-resnet#93]
I run the command line 'python evaluate.py' to test the model with the VOC 2012 val set(1447 images), but the mIoU is bad, 0.047, what's wrong with my test?

**Comment by mokii** [comment]
OK,I look into #65 and use the SegmentationClassAug instead the val labels in the original VOC2012 dataset.But the label seems to be binary images and have no class information.How can I evaluate the 21-class VOC data?

**Comment by siinem** [comment]
hi mokii
could you solve this problem?

**Comment by mokii** [comment]
I have solved it. We are supposed to use labels in the VOC2012 augmentation dataset instead of the voc2012 dataset. 
Because in voc2012 dataset, the classes are represented with pixel value from 0-255, but in voc2012 augmentation dataset, the pixels are represented with value from 0-20.

**Comment by siinem** [comment]
Yep, when i used the annotations at the folder of SegmentationClassAug, the problem solved, too.
