### ISSUE TITLE
Resume my training

### ISSUE THREAD

**Issue by mokii** [DrSleep/tensorflow-deeplab-resnet#94]
My training breaks up and I want to resume my training, but find three kind of .ckpt file, .meta file, .index file or the data-00000-of-00001 file.Which one should I restore from?
I restore the data-00000-of-00001 file, but  got Data loss error.
what should I do?

**Comment by DrSleep** [comment]
How do you restore exactly?
If you provide a path like this `/mypath/myfilename.ckpt-data00000` this will give you an error. You should use `/mypath/myfilename.ckpt` instead. 

Refer to [this issue](https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/36) for more details
