### ISSUE TITLE
Tensorboard does not show any information

### ISSUE THREAD

**Issue by vijayg78** [DrSleep/tensorflow-deeplab-resnet#95]
Hi,
I am running the training from scratch with train.py with PASCAL VOC data set. Even after a lot of iterations the Tensorboard does not show up any information. Any solution for that? I am using tensorflow GPU 1.2.0.

Regards, Vijay

**Comment by DrSleep** [comment]
Do you have any tensorboard files in the `snapshot_dir` folder?

> tensorflow GPU 1.2.0

I have not tested the code with tensorflow higher than 1.1.0, so it might also be the cause of your problem

**Comment by vijayg78** [comment]
the check-point files were there i the folder. few  events files were also there in the folder.

**Comment by vijayg78** [comment]
Even on tensorflow 1.1.0 ubuntu 14.04 the tensorflow is coming up. Anyone faced similar issues?

**Comment by DrSleep** [comment]
> I am getting the images part of it, but not able to visualize loss and accuracy.

Only images are being dumped to tensorboard. You can easily add more summaries yourself. Please refer to the tensorboard documentation for further information.
