### ISSUE TITLE
Can't transform ResNet101.npy into ckpt

### ISSUE THREAD

**Issue by yjl9122** [DrSleep/tensorflow-deeplab-resnet#97]
ValueError: Variable fc1000/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I use your code to transform, but I get something wrong. Is there any one knows?

**Comment by DrSleep** [comment]
how does your model.py look like?

**Comment by yjl9122** [comment]
model.py is the same as yours

**Comment by DrSleep** [comment]
could you post the whole error message?

**Comment by yjl9122** [comment]
Oh, I have solved the problem. First I transform caffemodel to npy with your code, then i run sess with my own code. Thank you!
