### ISSUE TITLE
label seems to be not normal

### ISSUE THREAD

**Issue by meijieru** [DrSleep/tensorflow-deeplab-resnet#98]
I check the label read from disk (by `tf.unique`), the `tf.image.decode_png` does not read out the correct label. Is it possible?

```
In [36]: a = tf.image.decode_png(tf.read_file("/data/VOCdevkit/VOC2012/SegmentationClass/2007_000032.png"), channels=1)                                                    

In [37]: b = tf.reshape(a, [-1])       

In [38]: c = tf.unique(b)              

In [39]: sess.run(c)                   
Out[39]: Unique(y=array([  0, 220,  38, 147], dtype=uint8), idx=array([0, 0, 0, ..., 0, 0, 0], dtype=int32))
```

**Comment by DrSleep** [comment]
From [README](https://github.com/DrSleep/tensorflow-deeplab-resnet#using-your-dataset):

> Make sure that your segmentation masks are in the same format as the ones in the DeepLab setup (i.e., without a colour map). This means that if your segmentation masks are RGB images, you would need to convert each 3-D RGB vector into a 1-D label

Plus the same question has been asked at least twice before: https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/43, https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/79
