### ISSUE TITLE
How does the label encoding work?

### ISSUE THREAD

**Issue by akshittyagi** [DrSleep/tensorflow-deeplab-resnet#99]
The label is initially an image read as a 3 channel image with pixel values. How is it converted into a pixel-wise map of labels? As in when does, it get the marking of labels?

Init label image: at each pixel, we have a (3,) vector with channel colors
Training label: at each pixel, we have a marking of which class it belongs to

When does this transformation take place?

**Comment by DrSleep** [comment]
Please read this [comment](https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/98#issuecomment-314019935); and check out the official DeepLab [FAQ](https://ccvl.stat.ucla.edu/deeplab_faq/).

The labels are converted into the ones without a colour map before the training process starts.
